### PR TITLE
added reqCallback to use this callback to edit request before sending

### PR DESCRIPTION
**Pull request by RavilKalimullin**

### CODE REVIEW

**Comment by Rob--W** [comment]
What's the purpose of this?

**Comment by RavilKalimullin** [comment]
To edit request before sending

**Comment by yuyaryshev** [comment]
Use case we needed in our project was to change values of some headers (not to remove or add, but to change it).

**Comment by Rob--W** [comment]
Thanks for the explanation.

I have just pushed a commit with tested functionality that you can use for the same purpose: https://github.com/Rob--W/cors-anywhere/commit/9f1af8243463ab71b63b889fff5606bd908f36cc

That should address the needs from this PR, so I'll close it.

**Pull request closed without merging**
