### PR TITLE
WIP: upgrade http-proxy to 1.18.1

### PR DESCRIPTION
**Pull request by geekdada**
The failing tests relate to these changes https://github.com/http-party/node-http-proxy/compare/1.14.0...1.15.0

1. `Proxy errors Invalid HTTP status code`

http-proxy changed the way it sets the status code, so the error became uncaught.

2. `Proxy errors Content-Encoding invalid body`

I'm not sure why it behaves like this.

3. `x-forwarded-host` is a newly added header, I changed some testing code accordingly.

The reset would be solved once 1 and 2 are solved.

### CODE REVIEW

**Comment by Rob--W** [comment]
Question: Why do you want to upgrade the http-proxy dependency? Is there any functionality that upgrading would unlock?

The cors-anywhere source code monkey-patches the library and documents where it relies on (undocumented) http-proxy internals, Ctrl-F "node-http-proxy" in https://github.com/Rob--W/cors-anywhere/blob/a0309e6c475036b4ba2a04372f8d5b6462bd4825/lib/cors-anywhere.js

When the dependency is upgraded, I need to verify whether the assumptions are still true, whether there are other API changes and whether there are other regressions (e.g. uncaught errors, increased resource usage (memory, CPU, sockets, ...)). This takes some effort, and I am only willing to do that if there are benefits to upgrading.

**Comment by geekdada** [comment]
http-proxy used some weird require pattern so it won't work in Vercel. Vercel analyses the dependencies of an application, the pattern makes some parts in http-proxy to be treated as unused.

**Comment by Rob--W** [comment]
Given that use case, I would suggest to submit a patch to Vercel to support the directory import type. That fixes the problem at the root. A directory as an import is a valid value for `require`, see https://nodejs.org/dist/latest-v14.x/docs/api/modules.html#modules_all_together

**Comment by geekdada** [comment]
I totally agree with you. I just think it seems viable to upgrade http-proxy without changing too much.

Does `Proxy errors Content-Encoding invalid body` relate to the parts that you mentioned?

**Comment by Rob--W** [comment]
This is the commit where the test and logic was introduced (you can use git blame and look at the commit near the line of interest to find this): https://github.com/Rob--W/cors-anywhere/commit/35932a0ac106a81c5d71e479314a3ddbe4518868

The purpose of the test is to verify that the request/response is properly ended when an error occurs after sending the response head. Based on the test failure, it seems that the given test case does not trigger that error condition any more, so an alternative is needed to ensure that the server does really end the request. The test proved its value in 7222fce684c0c076be7bac4703f341735d48d8fa and I don't want to lose the test coverage for it. Finding that alternative may take some effort though.

**Comment by geekdada** [comment]
I'll take some time and have a look. 😉

**Comment by geekdada** [comment]
Multiple changes of the newer version of http-proxy make those error uncatchable, causing `http.Server` to crash. I don't think there's anything we could do in cors-anywhere to prevent that.

Close the pr.

**Pull request closed without merging**
