### PR TITLE
ability to use proxy handler in independent way (attach to express for example)

### PR DESCRIPTION
**Pull request by vladimiry**
I want to use this proxy as express middleware/handler (mapped to some mount path). Header "x-cors-anywhere-url" added to simplify obtaining URL in this case.

### CODE REVIEW

**Comment by unity** [comment]
Here's our attempt at it https://github.com/hull/cors-anywhere/commit/d046e52d99836dbc77648b129db2c36b1a3c55b7

**Comment by Rob--W** [comment]
@unity And how did you use that in production (in an express app, presumably)?

If you're interested in having such functionality in the core of CORS Anywhere, create a new issue with the use case and desired API. Though not required, it would also be nice if you send a PR with the functionality and/or unit tests.

**Comment by unity** [comment]
Sure, If you're interested in having it I will do a proper PR. We use it in an express app indeed. 

I thought since you were closing the issue it would be beneficial to mention our patch, either for further work or for people looking for a solution.



Sent from a small device with no real keyboard. 

Schedule some time with me: calendly.com/romain

**Comment by Rob--W** [comment]
@unity The issue was closed not because I'm opposed to the feature, but because the patch author expressed that the patch did not work as expected, and it hasn't been touched for quite some time.

If you submit a PR, I'll happily review and merge it.

**Pull request closed without merging**
