### PR TITLE
Doco for AWS and Greylist

### PR DESCRIPTION
**Pull request by hutch120**
Hi All,

I've implemented this library on AWS and thought others might have a use for my changes.

Essentially I've updated two sections in this pull request.

1) Some doco changes that provide tips to implementing on AWS

2) A Greylist which is a bit more open than a strict whitelist, and is there to allow multiple subdomains without having to specify each one. Could have done this with a string.endswith rather than indexOf to tighten this up... but anyway, here it is.

### CODE REVIEW

**Comment by hutch120** [comment]
Can someone let me know why my code has caused coverage to decrease? I can't see the issue.

**Comment by Rob--W** [comment]
> Can someone let me know why my code has caused coverage to decrease? I can't see the issue.

The coverage decreased because you added new logic without unit tests. Click on "Details" next to coveralls and click on the lib/cors-anywhere.js at the "Source files on build 34". Then the parts without coverage are shown in red.

The whitelist and blacklist are for exact origin matches, if you wish more flexibility, use the `checkRateLimit` option (which defaults to the implementation in https://github.com/Rob--W/cors-anywhere/blob/master/lib/rate-limit.js (see this file for the configuration syntax)). This logic can be configured via the `CORSANYWHERE_RATELIMIT` environment variable (also mentioned in the [README](https://github.com/Rob--W/cors-anywhere#demo-server)). For example (this example is taken from the comment in the source code in lib/rate-limit.js:

```sh
# Allow example.com, or any subdomain to make any number of requests and block the rest:
export CORSANYWHERE_RATELIMIT='0 1 /(.*\.)?example\.com/'
```

**Comment by hutch120** [comment]
@Rob--W Ah, cool. Thanks for the feedback. Re-read the doco and I see the bit now about subdomains now... don't know how I missed that. 

Perhaps consider just the AWS doco as part of the pull request. It took me a while to figure out the Software Configuration section was where to put the environment variables, and that you had to set _Query String Forwarding and Caching_ to _Forward all_ in Cloudfront in order to get an SSL enabled proxy.

Cheers,
SImon

**Comment by Rob--W** [comment]
I think that I will pass on this PR, since it seems to have very little to do with this library itself and it is really specific to AWS. Those who have zero experience with AWS won't be able to set up the application since the tips alone cannot be used to get started. Those who have already set up a Node.js application on AWS will likely not have issues with setting up their custom CORS Anywhere instance.

I have seen a question before about AWS Lambda (#38); If you think that your tips are related I encourage you to post your tips in a comment in #38.

**Pull request closed without merging**
